---
- name: Install list of packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
  - vim 
  - git
  - hwinfo

- name: Update all packages to the latest version
  apt: update_cache=yes upgrade=dist
